sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jjw3HBmgclXOgCEr96zfZiqqUNIu5w4GA3b03wIPajLcDFD1WmghwRbiU4WPGB16OS0NJcI7QKHhtgRABRLfnWYVke8QB1QDwoHTBRlBRTYE2MyDoNwvtQ62tfW3QMAoTD/tYqYztpgSBsVG6m6jxNJkAYpdjW55x/SE4PQhRuBAkalUCYLOj1V1S2OZ5um9SalXg3uFqwXNoWOwokv06i75JdDAROOL+rLV7AqGJ2c5WneOGE7K/OFWwdF/5Ba3IqxjmmvtU6Y3ojGZkrDjrDmR1E4C/2I+NwDWn7oGNussdGaPhzgWGIxdqXYQgl1LpNoH/kZSXrwldz7yXJyXWIvoXbbtPu2e4Lhk9ZBM90+g/gKOSdML8I29S/VQO6FVe9O2AFddpssVVonAPBJPx6GBkia4yo8avK/AyWkjaGR5dId8sibCQgUY6QEcdi/0V1MneXPh8OsGqUwGzlAt2lVI5e9ufWNQoFz+1sQ/UkWXEvo0GXkzMB9MNB6p9J0BagM9iAMWwZW9RzFBesz1r0fnbxKwiEyGVMWSvXUGJNFfBz3v8rAUlyknETpFslXUG7D+BEHlj1MWpdRS/0Hh4JpzOtF+KOezV7UMg3oM1N+Vpu+2k6DPuL5+gVmN/ZECU+u9rcdlQULInJ7YREdbTbK16CkI5TXmqXFAM3APWgU=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Divine-Comedy-Cary-s-Translation-Purgatory_1006
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy